### ISSUE TITLE
Possible expansion to include other data operations.

### ISSUE THREAD

**Issue by Peter-Van-Drunen** [AbdullahAli/node-stream-to-mongo-db#7]
I was using this as a quick way of streaming some data into my local mongodb instance for a pet project and I need to not only insert, but also update. I could make a PR with some changes that allow multiple operations (update, stream delete based on index, etc.) If that is something the owner of this repository is interested in pursuing.

Let me know what you think @AbdullahAli

**Comment by fabienjuif** [comment]
I think this is a good idea.
We could pass the callback (operation) into options.
And its default value is the insert we do here: https://github.com/AbdullahAli/node-stream-to-mongo-db/blob/master/src/index.js#L23

The lib should still take care of batching array :)

Feel free to open a PR we could better argue with it ;)

**Comment by AbdullahAli** [comment]
Hi @Peter-Van-Drunen 

Thank you for the suggestion - it sounds like a great idea 👍 

Please feel free to open a PR and ping either @fabienjuif or myself for assistance/review

Looking forward to it

**Comment by AbdullahAli** [comment]
Addressed by: https://github.com/AbdullahAli/node-stream-to-mongo-db/pull/6 👍
